[package]
name = "usecase"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
mockall = "0.10"
derive-new = "0.5"
anyhow = "1.0"
thiserror = "1.0"
