version: "3"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - CARGO_BUILD_TARGET_DIR=/cache/target
      - DATABASE_URL=postgres://postgres:postgres@localhost/peta
    tty: true
    working_dir: /workspace
    volumes:
      - ..:/workspace:delegated
      - cache-rust-target:/cache/target
    network_mode: service:db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    init: true

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  cache-rust-target:
  postgres-data:
