name: backend/fusen

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash
    working-directory: ./backend/fusen

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --workspace

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Format codes
        run: cargo fmt --all -- --check
      - name: Lint codes
        run: cargo clippy -- -D warnings
