name: backend/recommendation

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash
    working-directory: ./backend/recommendation

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --workspace

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format codes
        run: cargo fmt --all -- --check
      - name: Lint codes
        run: cargo clippy -- -D warnings
